'use strict'
const Skin = use('App/Models/Skin')
const Config = use('App/Models/Config')
const Ref = use('App/Models/Ref')

/** @type {import('@adonisjs/lucid/src/Factory')} */
const Factory = use('Factory')

class SkinSeeder {
  async run () {
    // SEED SKINS
    const skin = await Skin.create({ key: 'alien-bag', name: 'Alien Bag', image: '/assets/img/skins/weekly/alien-bag/' })
    await Skin.create({ key: 'armor1', name: 'Soldier Armour', image: '/assets/img/skins/weekly/armor1/' })
    await Skin.create({ key: 'somurai', name: 'Utaka', image: '/assets/img/skins/weekly/somurai/' })
    await Skin.create({ key: 'squid', name: 'Squidy Helmet', image: '/assets/img/skins/weekly/squid/' })
    await Skin.create({ key: 'sultan', name: 'Sultan Hat', image: '/assets/img/skins/weekly/sultan/' })
    await Skin.create({ key: 'sword', name: 'Simple Sword', image: '/assets/img/skins/weekly/sword/' })
    await Skin.create({ key: 'sword-double', name: 'Double Sword', image: '/assets/img/skins/weekly/sword-double/' })
    await Skin.create({ key: 'sword-other', name: 'Blader', image: '/assets/img/skins/weekly/sword-other/' })
    await Skin.create({ key: 'sword-scifi', name: 'VR Blade', image: '/assets/img/skins/weekly/sword-scifi/' })
    await Skin.create({ key: 'sword2', name: 'Metallic', image: '/assets/img/skins/weekly/sword2/' })
    await Skin.create({ key: 'sword3', name: 'Espada', image: '/assets/img/skins/weekly/sword3/' })
    await Skin.create({ key: 'sword4', name: 'Furia', image: '/assets/img/skins/weekly/sword4/' })
    await Skin.create({ key: 'sword5', name: 'Titanfall', image: '/assets/img/skins/weekly/sword5/' })
    await Skin.create({ key: 'sword6', name: 'Cutlass', image: '/assets/img/skins/weekly/sword6/' })
    await Skin.create({ key: 'tiger', name: 'Tiger Helmet', image: '/assets/img/skins/weekly/tiger/' })
    await Skin.create({ key: 'trump', name: 'POTUS Helmet', image: '/assets/img/skins/weekly/trump/' })
    await Skin.create({ key: 'turban', name: 'Turban hat', image: '/assets/img/skins/weekly/turban/' })
    await Skin.create({ key: 'unicorn', name: 'Unicorn Helmet', image: '/assets/img/skins/weekly/unicorn/' })
    await Skin.create({ key: 'welder', name: 'Welder Helmet', image: '/assets/img/skins/weekly/welder/' })
    await Skin.create({ key: 'western-shotgun', name: 'Western Shotgun', image: '/assets/img/skins/weekly/western-shotgun/' })
    await Skin.create({ key: 'worker', name: 'Worker Helmet', image: '/assets/img/skins/weekly/worker/' })
    await Skin.create({ key: 'yellow', name: 'Yellow Helmet', image: '/assets/img/skins/weekly/yellow/' })
    await Skin.create({ key: 'zombieaxe', name: 'Zombie Lover', image: '/assets/img/skins/weekly/zombieaxe/' })
    await Skin.create({ key: 'machete2', name: "Orch's Wife", image: '/assets/img/skins/weekly/machete2/' })
    await Skin.create({ key: 'mask', name: 'Simple Mask', image: '/assets/img/skins/weekly/mask/' })
    await Skin.create({ key: 'maskblack', name: 'Dark Mask', image: '/assets/img/skins/weekly/maskblack/' })
    await Skin.create({ key: 'medusa', name: 'Medusa', image: '/assets/img/skins/weekly/medusa/' })
    await Skin.create({ key: 'mexican', name: "Mariachi's Hat", image: '/assets/img/skins/weekly/mexican/' })
    await Skin.create({ key: 'nazi', name: 'Nein Hat', image: '/assets/img/skins/weekly/nazi/' })
    await Skin.create({ key: 'panda', name: 'Panda Helmet', image: '/assets/img/skins/weekly/panda/' })
    await Skin.create({ key: 'paperbag', name: 'Paperbag Helmmet', image: '/assets/img/skins/weekly/paperbag/' })
    await Skin.create({ key: 'party', name: "Birthday's Hat", image: '/assets/img/skins/weekly/party/' })
    await Skin.create({ key: 'phones', name: 'Headphones', image: '/assets/img/skins/weekly/phones/' })
    await Skin.create({ key: 'pistol', name: 'Golden Eagle', image: '/assets/img/skins/weekly/pistol/' })
    await Skin.create({ key: 'pistol-2-scifi', name: 'Infinity 8mm', image: '/assets/img/skins/weekly/pistol-2-scifi/' })
    await Skin.create({ key: 'pistol-scifi', name: 'VR Pistol', image: '/assets/img/skins/weekly/pistol-scifi/' })
    await Skin.create({ key: 'police', name: 'Policeman Hat', image: '/assets/img/skins/weekly/police/' })
    await Skin.create({ key: 'racoon', name: 'Racoon Helmet', image: '/assets/img/skins/weekly/racoon/' })
    await Skin.create({ key: 'rifle', name: 'Golden AK47', image: '/assets/img/skins/weekly/rifle/' })
    await Skin.create({ key: 'rifle-2-scifi', name: 'VR Terminator', image: '/assets/img/skins/weekly/rifle-2-scifi/' })
    await Skin.create({ key: 'rifle-3-scifi', name: 'Laser Stopper', image: '/assets/img/skins/weekly/rifle-3-scifi/' })
    await Skin.create({ key: 'rifle-scifi', name: 'Infinity Barrel', image: '/assets/img/skins/weekly/rifle-scifi/' })
    await Skin.create({ key: 'roadcone', name: 'Roadcone Hat', image: '/assets/img/skins/weekly/roadcone/' })
    await Skin.create({ key: 'roman', name: "Cesar's Helmet", image: '/assets/img/skins/weekly/roman/' })
    await Skin.create({ key: 'samu-mask', name: 'Kung Helmet', image: '/assets/img/skins/weekly/samu-mask/' })
    await Skin.create({ key: 'lanza', name: 'Fu Lanza', image: '/assets/img/skins/weekly/lanza/' })
    await Skin.create({ key: 'shark', name: 'Shark Helmet', image: '/assets/img/skins/weekly/shark/' })
    await Skin.create({ key: 'shotgun', name: 'Benelli Shotgun', image: '/assets/img/skins/weekly/shotgun/' })
    await Skin.create({ key: 'skull', name: 'Skull Hat', image: '/assets/img/skins/weekly/skull/' })
    await Skin.create({ key: 'skull-face', name: 'Skull Mask', image: '/assets/img/skins/weekly/skull-face/' })
    await Skin.create({ key: 'slayer', name: 'Slayer', image: '/assets/img/skins/weekly/slayer/' })
    await Skin.create({ key: 'smg', name: 'Infinity SMG', image: '/assets/img/skins/weekly/smg/' })
    await Skin.create({ key: 'armor2', name: 'Lieutenant Armour', image: '/assets/img/skins/weekly/armor2/' })
    await Skin.create({ key: 'armor3', name: 'Captain Armour', image: '/assets/img/skins/weekly/armor3/' })
    await Skin.create({ key: 'axe', name: 'Axy', image: '/assets/img/skins/weekly/axe/' })
    await Skin.create({ key: 'axe-long', name: 'Dayton Axe', image: '/assets/img/skins/weekly/axe-long/' })
    await Skin.create({ key: 'axe-long2', name: 'Kentucky Axe', image: '/assets/img/skins/weekly/axe-long2/' })
    await Skin.create({ key: 'axe-long3', name: 'Yankee Axe', image: '/assets/img/skins/weekly/axe-long3/' })
    await Skin.create({ key: 'axe-long4', name: 'Humboldt Axe', image: '/assets/img/skins/weekly/axe-long4/' })
    await Skin.create({ key: 'axe-other', name: 'Wedge Axe', image: '/assets/img/skins/weekly/axe-other/' })
    await Skin.create({ key: 'axe-other2', name: 'Swamping Axe', image: '/assets/img/skins/weekly/axe-other2/' })
    await Skin.create({ key: 'axe2', name: 'Narrow Swamping Axe', image: '/assets/img/skins/weekly/axe2/' })
    await Skin.create({ key: 'axe3', name: 'Turpintine Axe', image: '/assets/img/skins/weekly/axe3/' })
    await Skin.create({ key: 'axe4', name: 'Virginia Axe', image: '/assets/img/skins/weekly/axe4/' })
    await Skin.create({ key: 'axe5', name: 'Rockaway Axe', image: '/assets/img/skins/weekly/axe5/' })
    await Skin.create({ key: 'bag1', name: 'Sports Bag', image: '/assets/img/skins/weekly/bag1/' })
    await Skin.create({ key: 'bag2', name: 'Camping Bag', image: '/assets/img/skins/weekly/bag2/' })
    await Skin.create({ key: 'bag3', name: 'Nomad Bag', image: '/assets/img/skins/weekly/bag3/' })
    await Skin.create({ key: 'bayonet', name: 'Bayonet', image: '/assets/img/skins/weekly/bayonet/' })
    await Skin.create({ key: 'double-sword-scifi', name: 'Infinity Sword', image: '/assets/img/skins/weekly/double-sword-scify/' })
    await Skin.create({ key: 'gem', name: 'Gem', image: '/assets/img/skins/weekly/gem/' })
    await Skin.create({ key: 'halberd', name: 'Halberd', image: '/assets/img/skins/weekly/halberd/' })
    await Skin.create({ key: 'hammer', name: 'Ragnarok Hammer', image: '/assets/img/skins/weekly/hammer/' })
    await Skin.create({ key: 'hammer-other', name: 'Rubber Mallet Hammer', image: '/assets/img/skins/weekly/hammer-other/' })
    await Skin.create({ key: 'hammer-other2', name: 'Brass Hammer', image: '/assets/img/skins/weekly/hammer-other2/' })
    await Skin.create({ key: 'hammer2', name: 'Blacksmith Hammer', image: '/assets/img/skins/weekly/hammer2/' })
    await Skin.create({ key: 'alien', name: 'Alien Helmet', image: '/assets/img/skins/weekly/alien/' })
    await Skin.create({ key: 'army', name: 'Soldier Helmet', image: '/assets/img/skins/weekly/army/' })
    await Skin.create({ key: 'bunny', name: 'Bunny Helmet', image: '/assets/img/skins/weekly/bunny/' })
    await Skin.create({ key: 'chicken', name: 'Chicken Helmet', image: '/assets/img/skins/weekly/chicken/' })
    await Skin.create({ key: 'clown', name: 'Clown Helmet', image: '/assets/img/skins/weekly/clown/' })
    await Skin.create({ key: 'football', name: 'Football Helmet', image: '/assets/img/skins/weekly/football/' })
    await Skin.create({ key: 'fox', name: 'Fox Helmet', image: '/assets/img/skins/weekly/fox/' })
    await Skin.create({ key: 'horse', name: 'Horse Helmet', image: '/assets/img/skins/weekly/horse/' })
    await Skin.create({ key: 'icecream', name: 'Ice Cream Helmet', image: '/assets/img/skins/weekly/icecream/' })
    await Skin.create({ key: 'indian-hammer', name: 'Indian Hammer', image: '/assets/img/skins/weekly/indian-hammer/' })
    await Skin.create({ key: 'irish', name: 'Irish Helmet', image: '/assets/img/skins/weekly/irish/' })
    await Skin.create({ key: 'knight', name: 'Knight Helmet', image: '/assets/img/skins/weekly/knight/' })
    await Skin.create({ key: 'laser-scifi', name: 'Ghost Hunter', image: '/assets/img/skins/weekly/laser-scifi/' })
    await Skin.create({ key: 'lego', name: 'Block Helmet', image: '/assets/img/skins/weekly/lego/' })
    await Skin.create({ key: 'long-axe2', name: 'Main Axe', image: '/assets/img/skins/weekly/long-axe2/' })
    await Skin.create({ key: 'luchador', name: 'Wrestler Helmet', image: '/assets/img/skins/weekly/luchador/' })
    await Skin.create({ key: 'mace-blades', name: 'Mace Blade', image: '/assets/img/skins/weekly/mace-blades/' })
    await Skin.create({ key: 'machete', name: 'Silent Hilda', image: '/assets/img/skins/weekly/machete/' })

    //  SEED CONFIG
    await Config.create({ skin_id: skin.id })

    // SEED REFS
    await Ref.create({ key: 'bluewallet', source: 'BlueWallet', source_url: 'https://bluewallet.io/' })
    await Ref.create({ key: 'zap', source: 'Zap Wallet', source_url: 'https://zap.jackmallers.com/	' })
    await Ref.create({ key: 'lunaticoin', source: 'Lunaticoin Podcast', source_url: 'https://twitter.com/lunaticoin' })
    await Ref.create({ key: 'breez', source: 'Breez', source_url: 'https://breez.technology/' })
    await Ref.create({ key: 'satoshiwallet', source: 'Wallet of Satoshi', source_url: 'https://www.walletofsatoshi.com/' })
    await Ref.create({ key: 'cryptohulk', source: 'Crypto & Gamers', source_url: 'https://www.cryptoandgamers.com/' })
    await Ref.create({ key: 'muun', source: 'Muun Wallet', source_url: 'https://muun.com/' })
    await Ref.create({ key: 'tales', source: 'Tales from the Crypt', source_url: 'https://talesfromthecrypt.libsyn.com/' })
    await Ref.create({ key: 'vonbitcoin', source: 'Brekkie Von Bitcoin', source_url: 'https://www.vonbitcoin.com/' })
    await Ref.create({ key: 'bitcoin2020', source: 'Bitcoin2020 Conference', source_url: 'https://www.bitcoin2020conference.com/' })
    await Ref.create({ key: 'slp', source: 'Stephan Livera Podcast	', source_url: 'https://stephanlivera.com/' })
    await Ref.create({ key: 'vaultoro', source: 'Vaultoro', source_url: 'https://vaultoro.com/' })
  }
}

module.exports = SkinSeeder
